# Generated by Django 3.1.1 on 2020-10-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introCom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
