# Generated by Django 2.2.10 on 2020-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introCom', '0002_field_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Kiến trúc sư', 'Kiến trúc sư'), ('Thiết kế nội thất', 'Thiết kế nội thất'), ('Giám sát xây dựng', 'Giám sát xây dựng'), ('Kế toán', 'Kế toán')], max_length=200, null=True)),
                ('avatar', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images')),
            ],
        ),
    ]
