# Generated by Django 3.1.1 on 2020-11-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introCom', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
